### ISSUE TITLE
Sensibo sky crashes homebridge after upgrade to iOS 11.2.5

### ISSUE THREAD

**Issue by zork17** [wailuen/homebridge-sensibo-sky#18]
Hi,
The system worked for many months, but after the upgrade to 11.2.5, this plugin crashes and produce this log:
```
Jan 28 20:32:53 RSBPI homebridge[16953]: /usr/lib/node_modules/homebridge-sensibo-sky/lib/sensiboapi.js:117
Jan 28 20:32:53 RSBPI homebridge[16953]: callback(data.result[i].acState);
Jan 28 20:32:53 RSBPI homebridge[16953]: ^
Jan 28 20:32:53 RSBPI homebridge[16953]: TypeError: Cannot read property 'acState' of undefined
Jan 28 20:32:53 RSBPI homebridge[16953]: at /usr/lib/node_modules/homebridge-sensibo-sky/lib/sensiboapi.js:117:28
Jan 28 20:32:53 RSBPI homebridge[16953]: at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-sensibo-sky/lib/sensiboapi.js:50:21)
Jan 28 20:32:53 RSBPI homebridge[16953]: at emitNone (events.js:91:20)
Jan 28 20:32:53 RSBPI homebridge[16953]: at IncomingMessage.emit (events.js:185:7)
Jan 28 20:32:53 RSBPI homebridge[16953]: at endReadableNT (_stream_readable.js:974:12)
Jan 28 20:32:53 RSBPI homebridge[16953]: at _combinedTickCallback (internal/process/next_tick.js:74:11)
Jan 28 20:32:53 RSBPI homebridge[16953]: at process._tickCallback (internal/process/next_tick.js:98:9)
Jan 28 20:32:53 RSBPI systemd[1]: homebridge-nknx.service: main process exited, code=exited, status=1/FAILURE
```
I have the latest version: 0.4.2
This is the config.json:
```
		{
				"platform": "SensiboSky",
				"name": "Sensibo",
				"apiKey": "...",
				"ai": false,
				"hideFan": false, 
				"hideHumidity": true,
				"fixedState" : "manual"		
		},

```

**Comment by wailuen** [comment]
This is strange. I do not have this problem and I am also on 11.2.5. The log does indicate the plugin issue and i will more time as I had to relearn what i did more than 6 months ago. Maybe some guy can take over my project.

**Comment by zork17** [comment]
what do you mean by rebuild?
I tried to install another Sensibo plugin and got a similar error: Cannot read property 'acState' of undefined

**Comment by wailuen** [comment]
Well, guess this is an independent event. Will close this thread. Open another one if problem persists.
