### ISSUE TITLE
Getting weird errors on startup

### ISSUE THREAD

**Issue by jakesza** [wailuen/homebridge-sensibo-sky#34]
I keep getting the below errors on homebridge starrtup, If I remove the plugin, it works fine. 

my current config;
        {
            "platform": "SensiboSky",
            "name": "Sensibo",
            "apiKey": "apikey"
        }

error im getting:
/usr/local/lib/node_modules/homebridge/lib/api.js:50
  if (name.indexOf('.') == -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:50:12)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:296:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
[4/23/2019, 1:55:34 PM] Loaded config.json with 36 accessories and 1 platforms.

**Comment by leoneleone** [comment]
I'm getting no reponse issues in the home.app all of a sudden, not sure what its about :(

**Comment by Cloudore** [comment]
Mine is working OK (Gen 1) @leoneleone

**Comment by jakesza** [comment]
Mine also working fine. Maybe you have DNS issues?
