### ISSUE TITLE
Scenes not working properly?

### ISSUE THREAD

**Issue by Cloudore** [wailuen/homebridge-sensibo-sky#4]
Hey @wailuen,

Thanks again for the plug-in, which I use daily. The problem I'm experiencing is with my "Good morning" scene, which I have set to turn off my room's AC, turn on my lights, and coffee machine. The problem is, if my AC is already off (because I was too cold at 4am), instead of leaving it off, it'll most of the times turn it ON (sometimes it turns it on and then off again). 

It seems weird because if turn my AC off by the controller, leave it on in Sensibo and then turn it off through the Sensibo App, it'll stay off, which means from what I understand that the AC has a dedicated OFF command, this is a conclusion I came to through my troubleshooting however I'm not entirely sure.

Is there a way we can prevent this issue? maybe running some sort of check of state before sending out a power command? 

Regards

**Comment by wailuen** [comment]
I had made some minor changes and looks like it is fixed. Please try and let me know

**Comment by Cloudore** [comment]
Hmmm no idea why but this broke the plug in for me(Not responding), it seems like there is a state retrieving problem because before it updates and tells me not responding I can move the fan and It’ll push through to the pod. If there are any logs you want me to provide just tell me where to find them.

Thanks again

**Comment by wailuen** [comment]
Are u able to connect via the Sensibo app? Can u share your homebridge config?

Sometime, I lose connectivity even via the Sensibo app. The guy says I had bad wifi. But it recovers in 10 to 15 mins and life goes back to normal.

**Comment by Cloudore** [comment]
Sensibo is working alright, I lost connection from the home app as soon as I did npm update. Is it working perfectly for you?

> 
                {
                        "platform": "SensiboSky",
                        "name": "Sensibo",
                        "apiKey": "XkJtp5Ta5rPWA6gHSkhntVYRkh8Z6F",
                        "timeLapse": 50,
                        "ai": false,
                        "hideHumidity": false
                },

**Comment by wailuen** [comment]
Mine is working alright on my both homebridge. Depends on how you have your homebridge setup, the log are are different place. A look at the log might help. Or just run homebridge at the console and show me the output.

**Comment by Cloudore** [comment]
I think I got something worthwhile while trying to troubleshoot with the Terminal 

> Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-150 │     
    └────────────┘     
                       
[6/26/2017, 11:12:33 PM] Homebridge is running on port 51826.
[6/26/2017, 11:13:19 PM] Changed occupancy state for 10.0.1.155 to true. Last successful ping 2017-06-26T23:13:19+00:00 , last webhook none .
[6/26/2017, 11:13:19 PM] Updating  Zack   true
/usr/lib/node_modules/homebridge-sensibo-sky/accessories/pods.js:312
				callback(null, fanState(that.state.fanLevel));
				               ^

TypeError: fanState is not a function
    at null.<anonymous> (/usr/lib/node_modules/homebridge-sensibo-sky/accessories/pods.js:312:20)
    at emitThree (events.js:97:13)
    at emit (events.js:175:7)
    at Characteristic.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:120:10)
    at /usr/lib/node_modules/homebridge-sensibo-sky/accessories/pods.js:499:41
    at /usr/lib/node_modules/homebridge-sensibo-sky/accessories/pods.js:483:17
    at /usr/lib/node_modules/homebridge-sensibo-sky/lib/sensiboapi.js:127:5
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-sensibo-sky/lib/sensiboapi.js:50:21)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

Can you pinpoint a problem with this?

Thank you

**Comment by Cloudore** [comment]
Whoops I

**Comment by wailuen** [comment]
Sorry. Had introduced a bug while trying to get Fan AI up. Fixed for now. Please try and let me know for both this and the scene issue.

**Comment by Cloudore** [comment]
The plug-in is back up and running! Same problem while running the Good morning ac when the AC is already off though, it'll sometimes turn it on and off, and sometimes will turn it only back on

**Comment by wailuen** [comment]
It work in my test. Could you get me the output of the log after u activate the scence? Also tell me the state of the Aircon before u activate.

**Comment by Cloudore** [comment]
It seems like its working properly now that I'm trying to get the log! Let's try it for 48 hours, if the behavior stays as expected I will close the Issue.

Thanks @wailuen

**Comment by Cloudore** [comment]
The problem is still present, but it only appears after not using Home or the Sensibo app for hours. For example, in my Good morning scene, it happens every time, it will turn it on while I set it for off in the scene. The AC beeps twice, one for off, and one for on. Can it be something with the API maybe?

**Comment by wailuen** [comment]
Hmm.. Could u try with Ai to true? Let me know and I may be able to figure this out. Also, see if you can show me the log as well when u activate the scence. My test is working here and cannot simulate the issue.

**Comment by Cloudore** [comment]
I searched the whole system for a Homebridge.log file and I found one, which is empty for some reason. Is there something I should do to activate log keeping? I tried searching but I did not find a solution, will keep trying. I'll also try with ai: true and give you an update when I feel I've tried all scenarios.

Regards

**Comment by Cloudore** [comment]
Tried it again this morning with ai: true. Worked as expected with the Good morning scene; I then tried with my "good bye" scene (which turns my three ACs off with Sensibo), and my living room AC, which was already off, turned on. It is very weird that the issue isn't constant with all units.

I'm trying [this](https://github.com/nfarina/homebridge/issues/399) tonight get the log running so I can provide better info.

**Comment by Cloudore** [comment]
Think I got something:

This tests were made using the Goodbye scene, which turns off three(3) ACs. The "Sala" AC, Zack's AC, and Mack's AC.

Failed attempt (Zack's AC was already off, turned on)
>un 30 01:45:21 raspberrypi homebridge[1233]: [6/30/2017, 1:45:21 AM] [Television] websocket closed
Jun 30 01:45:23 raspberrypi homebridge[1233]: [6/30/2017, 1:45:23 AM] [Sala III] Success moving down (to 0)
Jun 30 01:45:32 raspberrypi homebridge[1233]: [6/30/2017, 1:45:32 AM] [Sala II] Success moving up (to 100)
Jun 30 01:45:35 raspberrypi homebridge[1233]: [6/30/2017, 1:45:35 AM] [Sensibo] Zack : Setting threshold (name:  Zack , threshold:  32 )
Jun 30 01:45:35 raspberrypi homebridge[1233]: [6/30/2017, 1:45:35 AM] [Sensibo] Lounge State change set, current ACstate: cool  new state: 0
Jun 30 01:45:35 raspberrypi homebridge[1233]: [6/30/2017, 1:45:35 AM] [Sensibo] Lounge  - Submit state change: New state:  cool On/Off Status: false
Jun 30 01:45:35 raspberrypi homebridge[1233]: [6/30/2017, 1:45:35 AM] [Sensibo] Zack State change set, current ACstate: cool  new state: 0
Jun 30 01:45:35 raspberrypi homebridge[1233]: [6/30/2017, 1:45:35 AM] [Sensibo] Zack  - Submit state change: New state:  cool On/Off Status: false
Jun 30 01:45:35 raspberrypi homebridge[1233]: [6/30/2017, 1:45:35 AM] [Sensibo] Mack : Setting threshold (name:  Mack , threshold:  32 )
Jun 30 01:45:35 raspberrypi homebridge[1233]: [6/30/2017, 1:45:35 AM] [Sensibo] Mack State change set, current ACstate: cool  new state: 0
Jun 30 01:45:35 raspberrypi homebridge[1233]: [6/30/2017, 1:45:35 AM] [Sensibo] Mack  - Submit state change: New state:  cool On/Off Status: false
Jun 30 01:45:35 raspberrypi homebridge[1233]: [6/30/2017, 1:45:35 AM] [Sensibo] Lounge : Setting threshold (name:  Lounge , threshold:  32 )
Jun 30 01:45:35 raspberrypi homebridge[1233]: [6/30/2017, 1:45:35 AM] [Sensibo] [DEBUG temp]  Lounge  Cur Target temp: 20  new targetTemp:  20
Jun 30 01:45:35 raspberrypi homebridge[1233]: [6/30/2017, 1:45:35 AM] [Sensibo] [DEBUG temp]  Mack  Cur Target temp: 21  new targetTemp:  21
Jun 30 01:45:35 raspberrypi homebridge[1233]: [6/30/2017, 1:45:35 AM] [Sensibo] [DEBUG temp]  Zack  Cur Target temp: 20  new targetTemp:  18
Jun 30 01:45:35 raspberrypi homebridge[1233]: [6/30/2017, 1:45:35 AM] [Sensibo] Zack  Submit new target temperature:  18
Jun 30 01:45:35 raspberrypi homebridge[1233]: [6/30/2017, 1:45:35 AM] [Sensibo] Changed status (name: Mack, roomTemp: 25.4, on: true, mode: cool, targetTemp: 21, speed: high)
Jun 30 01:45:35 raspberrypi homebridge[1233]: [6/30/2017, 1:45:35 AM] [Sensibo] Changed status (name: Lounge, roomTemp: 26.2, on: true, mode: cool, targetTemp: 20, speed: high)
Jun 30 01:45:35 raspberrypi homebridge[1233]: [6/30/2017, 1:45:35 AM] [Sensibo] Changed status (name: Zack, roomTemp: 22.7, on: true, mode: cool, targetTemp: 18, speed: high)
Jun 30 01:45:37 raspberrypi homebridge[1233]: [6/30/2017, 1:45:37 AM] [Sensibo] Changed status (name: Zack, roomTemp: 22.7, on: true, mode: cool, targetTemp: 18, speed: high)
Jun 30 01:45:48 raspberrypi homebridge[1233]: [6/30/2017, 1:45:48 AM] [Shutter Estudio] Success moving down (to 0)
Jun 30 01:45:57 raspberrypi homebridge[1233]: [6/30/2017, 1:45:57 AM] [Sala II] Success moving down (to 0)
Jun 30 01:46:02 raspberrypi homebridge[1233]: [6/30/2017, 1:46:02 AM] [Shutter Estudio] Success moving up (to 100)
Jun 30 01:46:14 raspberrypi sudo[6629]: pi : TTY=pts/0 ; PWD=/var ; USER=root ; COMMAND=/usr/bin/tee homebridgelog0.txt

Successful Attempt(Zack's AC was already off, turned on, then turned back off)
>Jun 30 01:44:10 raspberrypi homebridge[1233]: [6/30/2017, 1:44:10 AM] [Sensibo] Zack : Setting threshold (name:  Zack , threshold:  32 )
Jun 30 01:44:10 raspberrypi homebridge[1233]: [6/30/2017, 1:44:10 AM] [Sensibo] Lounge State change set, current ACstate: cool  new state: 0
Jun 30 01:44:10 raspberrypi homebridge[1233]: [6/30/2017, 1:44:10 AM] [Sensibo] Lounge  - Submit state change: New state:  cool On/Off Status: false
Jun 30 01:44:10 raspberrypi homebridge[1233]: [6/30/2017, 1:44:10 AM] [Sensibo] Zack State change set, current ACstate: cool  new state: 0
Jun 30 01:44:10 raspberrypi homebridge[1233]: [6/30/2017, 1:44:10 AM] [Sensibo] Zack  - Submit state change: New state:  cool On/Off Status: false
Jun 30 01:44:10 raspberrypi homebridge[1233]: [6/30/2017, 1:44:10 AM] [Sensibo] Mack : Setting threshold (name:  Mack , threshold:  32 )
Jun 30 01:44:10 raspberrypi homebridge[1233]: [6/30/2017, 1:44:10 AM] [Sensibo] Mack State change set, current ACstate: cool  new state: 0
Jun 30 01:44:10 raspberrypi homebridge[1233]: [6/30/2017, 1:44:10 AM] [Sensibo] Mack  - Submit state change: New state:  cool On/Off Status: false
Jun 30 01:44:10 raspberrypi homebridge[1233]: [6/30/2017, 1:44:10 AM] [Sensibo] Lounge : Setting threshold (name:  Lounge , threshold:  32 )
Jun 30 01:44:10 raspberrypi homebridge[1233]: [6/30/2017, 1:44:10 AM] [Sensibo] [DEBUG temp]  Lounge  Cur Target temp: 20  new targetTemp:  20
Jun 30 01:44:10 raspberrypi homebridge[1233]: [6/30/2017, 1:44:10 AM] [Sensibo] [DEBUG temp]  Mack  Cur Target temp: 21  new targetTemp:  21
Jun 30 01:44:10 raspberrypi homebridge[1233]: [6/30/2017, 1:44:10 AM] [Sensibo] [DEBUG temp]  Zack  Cur Target temp: 20  new targetTemp:  18
Jun 30 01:44:10 raspberrypi homebridge[1233]: [6/30/2017, 1:44:10 AM] [Sensibo] Zack  Submit new target temperature:  18

Hope this is useful

**Comment by wailuen** [comment]
I am also having same issue when I activate the scence. Somehow a random Aircon would be turn on when all of them are off. Still did not manage to find time to troubleshoot.

**Comment by wailuen** [comment]
This require more time to troubleshoot. Will try as soon as I can.

**Comment by Cloudore** [comment]
Thanks for the follow-up and all the work you've put in the plug-in.

In the hopes that you can solve the issue in this main repo, I think it'd be worth to mention that in @leoneleone's fork (https://github.com/leoneleone/homebridge-sensibo-sky), scenes work perfectly, I would need to try with hideFan(true) on yours, since all he did was place the rotation device inside the thermostat service and I had 0 issues since. I'll try this weekend when I can sit down and test some scenarios.

Regards

**Comment by wailuen** [comment]
Sorry.. disappeared for a while. I noticed my scene is working fine now which I had not done anything. Maybe something had chaned in Home app itself. Can you confirm ?

**Comment by Cloudore** [comment]
No worries, I had to do some changes a couple of weeks ago and was able to try this root plug in, unfortunately, the issue persisted. I have no idea why since I'm not much of a programmer and more of a tinkerer, but on my fork, this issue is not present.

**Comment by fserruto** [comment]
I'm having this issue too and resorted to IFTTT to turn off my Sensibo when used in a scene.  Is there anything I can do to help troubleshoot it?

**Comment by Cloudore** [comment]
@fab301s Do you have 1st gens or sky’s? I experience it on 1st gen

**Comment by fab301s** [comment]
1st gens, 4 units.

Cheers,
Fabian
